pipeline {
    agent any
    stages {
        stage('all-in-one: clean environment') { 
            steps { 
                sh '''
                	echo "Before clean environment:"
                	oc get all
                	oc delete all,template,daemonset,configmap -l jaeger-infra
                	echo "After clean environment:"
                	oc get all
                '''
            }
        }
        stage('all-in-one: deploy Jaeger') { 
            steps { 
                sh '''
                	echo "Before deploy jaeger:"
                	oc get all
                	oc process -f all-in-one/jaeger-all-in-one-template.yml | oc create -f -
                	echo "After deploy jaeger:"
                	oc get all
                '''
            }
        }
        stage('all-in-one: verify deployment'){
            steps {
                sh 'oc get dc'
                sh '''
                	sleep 5 # sleep some time to get proper deploy status
                	deployNameExpected="jaeger"
                	deployNameActual=`oc get deploy | grep "${deployNameExpected}" | awk '{print $1}'`
                	if [[ ${deployNameActual} != ${deployNameExpected} ]];then
                		echo "'${deployNameExpected}' not found, available list:"
                		oc get deploy
                		exit 1
                	else
                		echo "'${deployNameExpected}' found, available deploy list:"
                		oc get deploy
                	fi
                '''
            }
        }
        stage('all-in-one: verify services'){
            steps{
                sh 'oc get services'
                openshiftVerifyService apiURL: '', authToken: '', namespace: '', svcName: 'jaeger-query', verbose: 'true'
            }
        }
        stage('all-in-one: functional test'){
            steps{
                withEnv(["JAVA_HOME=${ tool 'jdk8' }", "PATH+MAVEN=${tool 'maven-3.5.0'}/bin:${env.JAVA_HOME}/bin"]) {
                    sh '''
                        export JAEGER_QUERY_HOST="jaeger-query.jaeger-ci.svc"
                        export JAEGER_AGENT_HOST="jaeger-agent.jaeger-ci.svc"
                        export JAEGER_PORT_QUERY_HTTP=80
                        export JAEGER_PORT_AGENT_ZIPKIN_THRIFT=5775
                        export JAEGER_PORT_AGENT_COMPACT=6831
                        export JAEGER_PORT_AGENT_BINARY=6832
                        export JAEGER_PORT_ZIPKIN_COLLECTOR=14268
                        rm ./jaeger-java-test -rf
                        git clone https://github.com/Hawkular-QE/jaeger-java-test.git
                        cd jaeger-java-test
                        mvn test
                    '''
                }
            }
        }
        stage('all-in-one: delete all') {
            steps {
                sh '''
                	echo "Before clean environment:"
                	oc get all
                	oc delete all,template,daemonset,configmap -l jaeger-infra
                	echo "After clean environment:"
                	oc get all
                '''
            }
        }
    }
}